=== Dovacat/tarkovquesthelper/schemas/quests.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "QuestName": {
            "type": "string"
        },
        "Locations": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Kappa": {
            "type": "boolean"
        },
        "LeadsTo": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Alternatives": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Requirements": {
            "type": "object",
            "properties": {
                "Level": {
                    "type": "integer"
                },
                "Quests": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                },
                "Items": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "Level"
            ]
        },
        "Objectives": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "Required": {
                            "type": "boolean"
                        },
                        "Location": {
                            "type": "string"
                        },
                        "LocationBoxTopLeft": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "integer"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "LocationBoxBottomRight": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "integer"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "Type": {
                            "type": "string"
                        },
                        "Time": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "number"
                                }
                            ]
                        },
                        "Target": {
                            "type": "string"
                        },
                        "Amount": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "Required",
                        "Location",
                        "LocationBoxTopLeft",
                        "LocationBoxBottomRight",
                        "Type",
                        "Time",
                        "Target",
                        "Amount"
                    ]
                }
            ]
        },
        "Rewards": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "Name": {
                            "type": "string"
                        },
                        "Amount": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "Name",
                        "Amount"
                    ]
                }
            ]
        }
    },
    "required": [
        "QuestName",
        "Locations",
        "Kappa",
        "LeadsTo",
        "Requirements",
        "Objectives",
        "Rewards"
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/ThePunisherPt4.json
{
    "QuestName": "The Punisher - Part 4",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "The Punisher - Part 5",
        "Kings Of The Rooftops"
    ],
    "Requirements": {
        "Level": 20,
        "Quests": [
            "The Punisher - Part 3"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "lighthouse",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "scavs using an 12ga shotgun",
            "Amount": 10
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "lighthouse",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "PMCs wearing a balaclava and scav vest",
            "Amount": 10
        },
        {
            "ID": 3,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "Bars A-2607 95Kh18 knive",
            "Amount": 5
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 18000
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.03
        },
        {
            "Name": "Roubles",
            "Amount": 100000
        },
        {
            "Name": "M4A1 SOPMOD II",
            "Amount": 1
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/ShootingCans.json
{
    "QuestName": "Shooting Cans",
    "Locations": [
        "ground_zero"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Debut",
        "The Good Times - Part 1"
    ],
    "Requirements": {
        "Level": 1
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "ground_zero",
            "LocationBoxTopLeft": [
                408,
                467
            ],
            "LocationBoxBottomRight": [
                443,
                487
            ],
            "Type": "scout",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "the Utyos machine gun",
            "Amount": 0
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "ground_zero",
            "LocationBoxTopLeft": [
                316,
                671
            ],
            "LocationBoxBottomRight": [
                363,
                708
            ],
            "Type": "scout",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "the AGS grenade launcher",
            "Amount": 0
        },
        {
            "ID": 3,
            "Required": true,
            "Location": "ground_zero",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "targets",
            "Amount": 5
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 1600
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.01
        },
        {
            "Name": "roubles",
            "Amount": 13000
        },
        {
            "Name": "Mosin infantry",
            "Amount": 1
        },
        {
            "Name": "7.62x54R FMJ ammo pack (20 rounds)",
            "Amount": 3
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/therapist/GeneralWares.json
{
    "QuestName": "General Wares",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Colleagues - Part 1"
    ],
    "Requirements": {
        "Level": 10,
        "Quests": [
            "Pharmacist"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "small tushonka",
            "Amount": 15
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 4800
        },
        {
            "Name": "Therapist rep",
            "Amount": 0.03
        },
        {
            "Name": "Roubles",
            "Amount": 30000
        },
        {
            "Name": "saury",
            "Amount": 4
        },
        {
            "Name": "iskra",
            "Amount": 2
        },
        {
            "Name": "coffee beans",
            "Amount": 2
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/therapist/SanitaryStandardsPt2.json
{
    "QuestName": "Sanitary Standards - Part 2",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Painkiller"
    ],
    "Requirements": {
        "Level": 8,
        "Quests": [
            "Sanitary Standards - Part 1"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "gas analyzer",
            "Amount": 2
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 4500
        },
        {
            "Name": "Therapist rep",
            "Amount": 0.03
        },
        {
            "Name": "Roubles",
            "Amount": 30000
        },
        {
            "Name": "Propital",
            "Amount": 1
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/ForgeAFriendship.json
{
    "QuestName": "Forge A Friendship",
    "Locations": [
        "shoreline"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Half Empty"
    ],
    "Requirements": {
        "Level": 1,
        "Quests": [
            "Hot Wheels",
            "Natural Exchange"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                428,
                891
            ],
            "LocationBoxBottomRight": [
                438,
                910
            ],
            "Type": "find",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "Prapor's cargo",
            "Amount": 0
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 18800
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 95000
        },
        {
            "Name": "AK-12",
            "Amount": 1
        },
        {
            "Name": "AK-74 45 round magazine",
            "Amount": 3
        },
        {
            "Name": "5.45x39 BP ammo pack (120 rounds)",
            "Amount": 2
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/therapist/OperationAquariusPt1.json
{
    "QuestName": "Operation Aquarius - Part 1",
    "Locations": [
        "customs"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Operation Aquarius - Part 2"
    ],
    "Requirements": {
        "Level": 6,
        "Quests": [
            "Shortage"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "customs",
            "LocationBoxTopLeft": [
                610,
                827
            ],
            "LocationBoxBottomRight": [
                626,
                844
            ],
            "Type": "scout",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "hidden water in the dorms",
            "Amount": 1
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 3300
        },
        {
            "Name": "Therapist rep",
            "Amount": 0.03
        },
        {
            "Name": "Skier rep",
            "Amount": -0.02
        },
        {
            "Name": "Roubles",
            "Amount": 14000
        },
        {
            "Name": "Water Bottle",
            "Amount": 5
        },
        {
            "Name": "Water Filter",
            "Amount": 1
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/KingsOfTheRooftops.json
{
    "QuestName": "Kings Of The Rooftops",
    "Locations": [
        "streets"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Best Job In The World"
    ],
    "Requirements": {
        "Level": 22,
        "Quests": [
            "The Punisher - Part 4"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "streets",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "sniper scavs",
            "Amount": 10
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 14700
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 77000
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/ThePunisherPt1.json
{
    "QuestName": "The Punisher - Part 1",
    "Locations": [
        "shoreline"
    ],
    "Kappa": true,
    "LeadsTo": [
        "The Punisher - Part 2"
    ],
    "Requirements": {
        "Level": 17,
        "Quests": [
            "Shaking Up The Teller"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "scavs using an AKM series weapon",
            "Amount": 15
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 10200
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 40000
        },
        {
            "Name": "6B43 Zabralo-Sh body armor",
            "Amount": 1
        },
        {
            "Name": "Purchase of SV-98 sniper rifle from prapor lvl 3",
            "Amount": 1
        },
        {
            "Name": "Purchase of 7.62x39 PS gzh from prapor lvl 3",
            "Amount": 1
        }
    ]
}
