=== Dovacat/tarkovquesthelper/schemas/quests.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "QuestName": {
            "type": "string"
        },
        "Locations": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Kappa": {
            "type": "boolean"
        },
        "LeadsTo": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Alternatives": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Requirements": {
            "type": "object",
            "properties": {
                "Level": {
                    "type": "integer"
                },
                "Quests": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                },
                "Items": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "Level"
            ]
        },
        "Objectives": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "Required": {
                            "type": "boolean"
                        },
                        "Location": {
                            "type": "string"
                        },
                        "LocationBoxTopLeft": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "integer"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "LocationBoxBottomRight": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "integer"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "Type": {
                            "type": "string"
                        },
                        "Time": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "number"
                                }
                            ]
                        },
                        "Target": {
                            "type": "string"
                        },
                        "Amount": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "Required",
                        "Location",
                        "LocationBoxTopLeft",
                        "LocationBoxBottomRight",
                        "Type",
                        "Time",
                        "Target",
                        "Amount"
                    ]
                }
            ]
        },
        "Rewards": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "Name": {
                            "type": "string"
                        },
                        "Amount": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "Name",
                        "Amount"
                    ]
                }
            ]
        }
    },
    "required": [
        "QuestName",
        "Locations",
        "Kappa",
        "LeadsTo",
        "Requirements",
        "Objectives",
        "Rewards"
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/Anesthesia.json
{
    "QuestName": "Anesthesia",
    "Locations": [
        "shoreline"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Rigged Game",
        "Samples",
        "Chemistry Closet"
    ],
    "Requirements": {
        "Level": 21,
        "Quests": [
            "Shaking Up The Teller"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                403,
                486
            ],
            "LocationBoxBottomRight": [
                406,
                491
            ],
            "Type": "mark",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "first trading post",
            "Amount": 1
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                218,
                616
            ],
            "LocationBoxBottomRight": [
                225,
                622
            ],
            "Type": "mark",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "second trading post",
            "Amount": 1
        },
        {
            "ID": 3,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                427,
                902
            ],
            "LocationBoxBottomRight": [
                430,
                908
            ],
            "Type": "mark",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "third trading post",
            "Amount": 1
        },
        {
            "ID": 4,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "survive",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "shoreline raid",
            "Amount": 1
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 18100
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.04
        },
        {
            "Name": "Roubles",
            "Amount": 50000
        },
        {
            "Name": "AS VAL",
            "Amount": 1
        },
        {
            "Name": "9x39 SPP ammo pack (20 rounds)",
            "Amount": 5
        },
        {
            "Name": "9x39 SP ammo pack (20 rounds)",
            "Amount": 5
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/HalfEmpty.json
{
    "QuestName": "Half Empty",
    "Locations": [
        "any"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Stick In The Wheel"
    ],
    "Requirements": {
        "Level": 1,
        "Quests": [
            "Forge A Friendship"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "military electronics items",
            "Amount": 5
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "computer component items",
            "Amount": 10
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 14900
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 123000
        },
        {
            "Name": "Altyn helmet",
            "Amount": 2
        },
        {
            "Name": "Altyn face shield",
            "Amount": 2
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/ShakingUpTheTeller.json
{
    "QuestName": "Shaking Up The Teller",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "The Punisher - Part 1",
        "Perfect Mediator",
        "Anethesia"
    ],
    "Requirements": {
        "Level": 10,
        "Quests": [
            "Ice Cream Cones"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "customs",
            "LocationBoxTopLeft": [
                85,
                78
            ],
            "LocationBoxBottomRight": [
                87,
                80
            ],
            "Type": "fetch",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "bank case",
            "Amount": 1
        },
        {
            "ID": 2,
            "Required": false,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "gather",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "dorm room 203 key",
            "Amount": 1
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 5900
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 75000
        },
        {
            "Name": "Geiger counter",
            "Amount": 1
        },
        {
            "Name": "Purchase of AKS-74U PBS-4 suppressor from prapor lvl 3",
            "Amount": 1
        },
        {
            "Name": "Purchase of Hexagon 12k suppressor from skier lvl 2",
            "Amount": 1
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/GendarmerieMallCop.json
{
    "QuestName": "Gendarmerie - Mall Cop",
    "Locations": [
        "streets"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Gendarmerie - Tickets, Please"
    ],
    "Requirements": {
        "Level": 1,
        "Quests": [
            "The Punisher - Part 6"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "streets",
            "LocationBoxTopLeft": [
                550,
                225
            ],
            "LocationBoxBottomRight": [
                686,
                371
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "targets using pistols",
            "Amount": 15
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 21500
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "roubles",
            "Amount": 120000
        },
        {
            "Name": "SR-2M",
            "Amount": 1
        },
        {
            "Name": "SR-2M 30 round magazine",
            "Amount": 4
        },
        {
            "Name": "9x21 PS gzh ammo pack (30 rounds)",
            "Amount": 5
        },
        {
            "Name": "barter for SR-1MP from Prapor level 4",
            "Amount": 1
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/therapist/Shortage.json
{
    "QuestName": "Shortage",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Sanitary Standards - Part 1",
        "Operation Aquarius - Part 1"
    ],
    "Requirements": {
        "Level": 1,
        "Quests": [
            "First In Line"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "salewa",
            "Amount": 3
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 2000
        },
        {
            "Name": "Therapist rep",
            "Amount": 0.03
        },
        {
            "Name": "Roubles",
            "Amount": 15000
        },
        {
            "Name": "Car first aid kit",
            "Amount": 2
        },
        {
            "Name": "Analgin painkillers",
            "Amount": 4
        },
        {
            "Name": "Splint",
            "Amount": 4
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/BigCustomer.json
{
    "QuestName": "Big Customer",
    "Locations": [
        "customs"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Trust Regain",
        "Loyalty Buyout",
        "Safe Corridor"
    ],
    "Alternatives": [
        "Chemical - Part 4",
        "Out Of Curiosity"
    ],
    "Requirements": {
        "Level": 1,
        "Quests": [
            "Chemical - Part 3"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "customs",
            "LocationBoxTopLeft": [
                189,
                370
            ],
            "LocationBoxBottomRight": [
                194,
                385
            ],
            "Type": "scout",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "the chemical transport",
            "Amount": 0
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "customs",
            "LocationBoxTopLeft": [
                189,
                370
            ],
            "LocationBoxBottomRight": [
                194,
                385
            ],
            "Type": "mark",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "the chemical transport",
            "Amount": 0
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 8100
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.03
        },
        {
            "Name": "Skier rep",
            "Amount": -0.25
        },
        {
            "Name": "Therapist rep",
            "Amount": -0.25
        },
        {
            "Name": "Roubles",
            "Amount": 200000
        },
        {
            "Name": "6B2",
            "Amount": 1
        },
        {
            "Name": "Ammunition case",
            "Amount": 2
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/TestDrivePt3.json
{
    "QuestName": "Test Drive - Part 3",
    "Locations": [
        "lighthouse"
    ],
    "Kappa": true,
    "Requirements": {
        "Level": 30,
        "Quests": [
            "Test Drive - Part 2"
        ]
    },
    "LeadsTo": [
        "Test Drive - Part 4"
    ],
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "lighthouse",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "eliminate",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "PMCs using the specified AK-12",
            "Amount": 20
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 35300
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 400000
        },
        {
            "Name": "RPK-16",
            "Amount": 1
        },
        {
            "Name": "AK-74 60 round magazine",
            "Amount": 4
        },
        {
            "Name": "545x39 7N40 ammo pack (30 rounds)",
            "Amount": 8
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/HellOnEarthPt1.json
{
    "QuestName": "Hell On Earth - Part 1",
    "Locations": [
        "any"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Hell On Earth - Part 2"
    ],
    "Requirements": {
        "Level": 1,
        "Quests": [
            "The Good Times - Part 1"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "modify",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "MP-43-1C",
            "Amount": 1
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 15600
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.01
        },
        {
            "Name": "roubles",
            "Amount": 35700
        },
        {
            "Name": "NPP KIASS body armor",
            "Amount": 2
        }
    ]
}
