=== Dovacat/tarkovquesthelper/schemas/quests.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "QuestName": {
            "type": "string"
        },
        "Locations": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Kappa": {
            "type": "boolean"
        },
        "LeadsTo": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Alternatives": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "Requirements": {
            "type": "object",
            "properties": {
                "Level": {
                    "type": "integer"
                },
                "Quests": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                },
                "Items": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "Level"
            ]
        },
        "Objectives": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "Required": {
                            "type": "boolean"
                        },
                        "Location": {
                            "type": "string"
                        },
                        "LocationBoxTopLeft": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "integer"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "LocationBoxBottomRight": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "integer"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "Type": {
                            "type": "string"
                        },
                        "Time": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "number"
                                }
                            ]
                        },
                        "Target": {
                            "type": "string"
                        },
                        "Amount": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "Required",
                        "Location",
                        "LocationBoxTopLeft",
                        "LocationBoxBottomRight",
                        "Type",
                        "Time",
                        "Target",
                        "Amount"
                    ]
                }
            ]
        },
        "Rewards": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "Name": {
                            "type": "string"
                        },
                        "Amount": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "Name",
                        "Amount"
                    ]
                }
            ]
        }
    },
    "required": [
        "QuestName",
        "Locations",
        "Kappa",
        "LeadsTo",
        "Requirements",
        "Objectives",
        "Rewards"
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/ThePunisherPt5.json
{
    "QuestName": "The Punisher - Part 5",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "The Punisher - Part 6",
        "Our Own Land"
    ],
    "Requirements": {
        "Level": 20,
        "Quests": [
            "The Punisher - Part 4"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "AK-74",
            "Amount": 1
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "M4A1",
            "Amount": 1
        },
        {
            "ID": 3,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "Makarov PM",
            "Amount": 2
        },
        {
            "ID": 4,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "PMCs wearing a PACA and 6B47 helmet",
            "Amount": 10
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 18200
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.03
        },
        {
            "Name": "Dollars",
            "Amount": 5000
        },
        {
            "Name": "Pistol case",
            "Amount": 1
        },
        {
            "Name": "Documents case",
            "Amount": 1
        },
        {
            "Name": "7.62x39 BP gzh ammo pack (20 rounds)",
            "Amount": 6
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/Debut.json
{
    "QuestName": "debut",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "search mission",
        "luxurious life"
    ],
    "Requirements": {
        "Level": 0,
        "Quests": [
            "shooting cans"
        ] 
    },
    "Objectives": [
        {
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "scav",
            "Amount": 5
        },
        {
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "gather",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "MP-133",
            "Amount": 2
        }

    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 1700
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Jaeger rep",
            "Amount": 0.01
        },
        {
            "Name": "Roubles",
            "Amount": 15000
        },
        {
            "Name": "PP-91 Kedr",
            "Amount": 1
        },
        {
            "Name": "9x18 PM BZhT gzh ammo pack (50 rounds)",
            "Amount": 2
        },
        {
            "Name": "Purchase AKS-74UB at Prapor lvl 1",
            "Amount": 1
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/ThePunisherPt6.json
{
    "QuestName": "The Punisher - Part 6",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Capturing Outposts",
        "Intimidator",
        "Escort",
        "The Choice",
        "Gendarmerie - Mall Cop",
        "Best Job In The World"
    ],
    "Requirements": {
        "Level": 21,
        "Quests": [
            "The Punisher - Part 5"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "PMCs using an SVD (not on factory)",
            "Amount": 15
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "BEAR dogtags",
            "Amount": 7
        },
        {
            "ID": 3,
            "Required": true,
            "Location": "any",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "fir",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "USEC Dogtags",
            "Amount": 7
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 19400
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.04
        },
        {
            "Name": "Therapist rep",
            "Amount": 0.05
        },
        {
            "Name": "Skier rep",
            "Amount": 0.01
        },
        {
            "Name": "Roubles",
            "Amount": 250000
        },
        {
            "Name": "Secure container epsilon",
            "Amount": 1
        },
        {
            "Name": "purchase of 7.62x54mm R PS gzh at Prapor lvl 4",
            "Amount": 1
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/TestDrivePt5.json
{
    "QuestName": "Test Drive - Part 5",
    "Locations": [
        "factory"
    ],
    "Kappa": true,
    "Requirements": {
        "Level": 40,
        "Quests": [
            "Test Drive - Part 4"
        ]
    },
    "LeadsTo": [
        "Test Drive - Part 6"
    ],
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "any targets using the specified UZI PRO",
            "Amount": 50
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 50000
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 500000
        },
        {
            "Name": "AS VAL",
            "Amount": 1
        },
        {
            "Name": "VSS/VAL 30 round magazine",
            "Amount": 3
        },
        {
            "Name": "9x39 BP ammo pack (20 rounds)",
            "Amount": 6
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/Viewer.json
{
    "QuestName": "Viewer",
    "Locations": [
        "any"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Serious Allegations"
    ],
    "Requirements": {
        "Level": 1,
        "Quests": [
            "Minute Of Fame"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "woods",
            "LocationBoxTopLeft": [
                617,
                502
            ],
            "LocationBoxBottomRight": [
                625,
                506
            ],
            "Type": "stash",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "wifi camera",
            "Amount": 1
        },
        {
            "ID": 2,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                501,
                953
            ],
            "LocationBoxBottomRight": [
                509,
                964
            ],
            "Type": "stash",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "wifi camera",
            "Amount": 1
        },
        {
            "ID": 3,
            "Required": true,
            "Location": "factory",
            "LocationBoxTopLeft": [
                60,
                265
            ],
            "LocationBoxBottomRight": [
                65,
                278
            ],
            "Type": "stash",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "wifi camera",
            "Amount": 1
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 74000
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "roubles",
            "Amount": 172000
        },
        {
            "Name": "Pevko light beer",
            "Amount": 5
        },
        {
            "Name": "Vodka",
            "Amount": 5
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/TheGoodTimesPt1.json
{
    "QuestName": "The Good Times - Part 1",
    "Locations": [
        "factory"
    ],
    "Kappa": false,
    "LeadsTo": [
        "Quality Standard",
        "Hell On Earth - Part 1"
    ],
    "Requirements": {
        "Level": 27,
        "Quests": [
            "Shooting Cans"
        ]
    },
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "factory",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "elimination",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "PMCs using the specified equipment",
            "Amount": 10
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 76000
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.03
        },
        {
            "Name": "roubles",
            "Amount": 256000
        },
        {
            "Name": "M1A",
            "Amount": 1
        },
        {
            "Name": "M1A 20 round magazine",
            "Amount": 2
        },
        {
            "Name": "7.62x51 M62 ammo pack (20 rounds)",
            "Amount": 3
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/BackgroundCheck.json
{
    "QuestName": "Background Check",
    "Locations": [
        "Customs"
    ],
    "Kappa": true,
    "LeadsTo": [
        "Shootout Picnic",
        "Delivery From the Past"
    ],
    "Requirements": {
        "Level": 0,
        "Quests": [
            "Luxurious Life"
        ],
        "Items": [
            "Machinery Key"
        ]
    },
    "Objectives": [
        {
            "Required": true,
            "Location": "Customs",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "Fetch",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "Bronze Pocket Watch",
            "Amount": 1
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 1800
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.03
        },
        {
            "Name": "Roubles",
            "Amount": 15000
        },
        {
            "Name": "SKS carbine",
            "Amount": 1
        },
        {
            "Name": "7.62x39 FMJ ammo pack (20 rounds)",
            "Amount": 3
        }
    ]
}

=== Dovacat/tarkovquesthelper/quests/prapor/TestDrivePt4.json
{
    "QuestName": "Test Drive - Part 4",
    "Locations": [
        "shoreline"
    ],
    "Kappa": true,
    "Requirements": {
        "Level": 40,
        "Quests": [
            "Test Drive - Part 3"
        ]
    },
    "LeadsTo": [
        "Test Drive - Part 5"
    ],
    "Objectives": [
        {
            "ID": 1,
            "Required": true,
            "Location": "shoreline",
            "LocationBoxTopLeft": [
                0,
                0
            ],
            "LocationBoxBottomRight": [
                0,
                0
            ],
            "Type": "eliminate",
            "Time": [
                0.0,
                0.0
            ],
            "Target": "any targets using the specified RPDN",
            "Amount": 30
        }
    ],
    "Rewards": [
        {
            "Name": "xp",
            "Amount": 40000
        },
        {
            "Name": "Prapor rep",
            "Amount": 0.02
        },
        {
            "Name": "Roubles",
            "Amount": 460000
        },
        {
            "Name": "AVT-40",
            "Amount": 1
        },
        {
            "Name": "AVT-40 15 round magazine",
            "Amount": 2
        },
        {
            "Name": "7.62x54 R SNB gzh ammo pack (20 rounds)",
            "Amount": 3
        }
    ]
}
